version: '3.8'

services:
  oobabot:
    build:
      context: .
      dockerfile: Dockerfile # change to Dockerfile.rocm for AMD GPUs
    container_name: oobabot
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # For AMD GPUs, comment out the `deploy:` block above and uncomment the below:
    #devices:
    #  - /dev/kfd
    #  - /dev/dri